2xxxx
Traceback (most recent call last):
  File "training_nn3_load_name.py", line 79, in <module>
    cuda_name = ["cuda:0","cuda:1"][int(sys.argv[1])]
IndexError: list index out of range
